### ISSUE TITLE
If there is only one layer in the project, cLayer will not get a value

### ISSUE THREAD

**Issue by FPhilipsen** [AlisterH/coveragebuilder#11]
Since cLayer (the coverage layer) is only set when the combobox on the menu is changed (I think), cLayer will/cannot not be set if there is only one layer loaded in the list.  
I would love to make a suggestion on how to fix that, but I'm new to Python, so I can't really help out yet.

**Comment by FPhilipsen** [comment]
I guess it also won't work if there are multiple layers to choose from, but the combobox defaults to the one you need as a coverage layer and you therefore don't change the value of the combobox. 

I think I might have some sort of a solution by copying line 110 to follow line 175 like so:
```
self.cLayer = self.dlg.ui.cbbInLayer.currentLayer()
```
second to last line below:

```
             if self.ladderOvrlpPercent <= 50 and self.ladderOvrlpPercent >= 0: #ajh: shouldn't need this check anymore
              self.overlapW = self.ladderWidth * self.ladderOvrlpPercent / 200;
              self.overlapH = self.ladderHeight * self.ladderOvrlpPercent / 200;
              self.ladderWidth = self.ladderWidth - self.overlapW * 2.;
              self.ladderHeight = self.ladderHeight - self.overlapH * 2.;
              self.cLayer = self.dlg.ui.cbbInLayer.currentLayer()
              if self.cLayer:
```
But please correct me if I'm breaking something by doing so.

Thanks for making this plugin by the way, I think it will come in handy on some of the projects I do!

**Comment by AlisterH** [comment]
Thanks, only just saw this.
I think:
- the problem is also if there is more than one layer, but the user doesn't specifically select one. 
- we can remove the other code and just keep the line you inserted.
